config/routes.rb
Longsword::Application.routes.draw do
  root 'home#index'
  match '/send_mail', to: 'contact#send_mail', via: 'post'
end

app/models/weather_condition.rb
class WeatherCondition < ActiveRecord::Base

  def self.get_current_weather
    key = ENV['WUNDERGROUND_KEY']
    puts "Fetching weather... "
    conditions = HTTParty.get(URI.encode("http://api.wunderground.com/api/#{key}/conditions/q/pws:KORJACKS10.json"))
    forecast = HTTParty.get(URI.encode("http://api.wunderground.com/api/#{key}/forecast/q/pws:KORJACKS10.json"))
    astronomy = HTTParty.get(URI.encode("http://api.wunderground.com/api/#{key}/astronomy/q/pws:KORJACKS10.json"))
    weather = WeatherCondition.new(:conditions => conditions.to_json, :forecast => forecast.to_json, :astronomy => astronomy.to_json)
    weather.save!

    if weather.save
      puts "Success"
    else
      puts "Error saving weather"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  layout "application"
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def send_mail
    name = params[:name]
    email = params[:email]
    body = params[:comments]
    ContactMailer.contact_email(name, email, body).deliver
    redirect_to root_path, notice: 'Thank you! Your message has been sent.'
  end

end

app/controllers/home_controller.rb
require 'json'

class HomeController < ApplicationController

  def index

    weather = WeatherCondition.last
    @weather_available = WeatherCondition.count > 0

    def valid_json?(json)
      begin
        JSON.parse(json)
        return true
      rescue JSON::ParserError
        return false
      end
    end

    valid_weather = valid_json?(weather.conditions) && valid_json?(weather.forecast) && valid_json?(weather.astronomy)

    if @weather_available && valid_weather
      conditions = JSON.parse(weather.conditions)
      forecast = JSON.parse(weather.forecast)
      astronomy = JSON.parse(weather.astronomy)

      @current_temp = conditions["current_observation"].present? ? conditions["current_observation"]["temp_f"] : 74.04
      @current_weather = conditions["current_observation"].present? ? conditions["current_observation"]["weather"] : "clear"
      @icon = conditions["current_observation"].present? ? conditions["current_observation"]["icon"] : "clear"

      @after_sunrise = astronomy["sun_phase"].present? ? (astronomy["sun_phase"]["sunrise"]["hour"].to_i > Time.now.hour) : false
      @before_sunrise = astronomy["sun_phase"].present? ? (Time.now.hour <= astronomy["sun_phase"]["sunrise"]["hour"].to_i) : false
      @after_close =  Time.now.hour >= 17 || Time.now.hour < 3

      @high = forecast["forecast"].present? ? forecast["forecast"]["simpleforecast"]["forecastday"][0]["high"]["fahrenheit"] : 74.04
      @high_tomorrow = forecast["forecast"].present? ? forecast["forecast"]["simpleforecast"]["forecastday"][1]["high"]["fahrenheit"] : 74.04
      @forecast = forecast["forecast"].present? ? forecast["forecast"]["simpleforecast"]["forecastday"][0]["conditions"] : "clear"
    else
      @weather_available = false
    end

    render "home/home"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-error"
    end
  end

end

app/views/home/home.html.haml
= content_for :css_placeholder do
  = stylesheet_link_tag 'manifests/home'
= content_for :js_placeholder do
  = javascript_include_tag 'manifests/home'

%header
  .header-wrapper.text-center
    .container
      .row
        .alert-container.col-md-6.col-md-offset-3
          - flash.each do |name, msg|
            - if msg.is_a?(String)
              %div{class: "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
                %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} ×
                = content_tag :div, msg, :id => "flash_#{name}"
      .row.flex
        .flex-item.text
          %h4 Visit Us
          %span{"data-toggle" => "modal", "data-target" => "#mapModal"} 8555 Highway 238, Jacksonville, OR 97530
          %a{:href =>"tel:+15418991746"}541.899.1746
        .flex-item.billboard.hidden-xs
        .flex-item.text
          %h4 Tasting Room Hours
          %p
            12-5pm every day
            |
            %a.contact-us{:href=>"#"} Contact Us

#navbar.navbar.navbar-inverse{role: "navigation"}
  .container
    .navbar-header
      %button#nav-toggle.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span
      %a.navbar-brand{:href => "#"}
        .global-lsv-logo
    .collapse.navbar-collapse.scrollspy-target
      %ul.nav.navbar-nav
        %li
          %a{href: "#visit", "data-close-nav" => "true"} Visit LongSword
        %li
          %a{href: "#wines", "data-close-nav" => "true"} Our Wines
        %li
          %a{href: "#about", "data-close-nav" => "true"} About Us
        %li.contact-link
          %a#contact{href: "javascript:void(0)"} Contact
      - if @weather_available
        %ul.nav.navbar-nav.navbar-right.hidden-sm
          -# %li.weather-icon-container
          -#   .weather{:class=> "weather-#{@icon}" + ((@after_sunset && @before_sunrise) ? "-night" : "")}
          %li.current-weather
            %a{href: "http://www.wunderground.com/personal-weather-station/dashboard?ID=KORJACKS10", target: "_blank"}
              Currently: #{@current_temp}&#186;F, #{@current_weather}
              %br
              #{@after_close ? "Tomorrow: #{@high_tomorrow}" : "Later: #{@high}"}&#186;F


  #contact-tray
    .container
      .row
        .col-md-5.col-md-offset-3.col-sm-7.col-sm-offset-2#contact-form
          = form_tag(send_mail_path) do
            .row
              .form-left
                .email
                  = email_field_tag 'email', nil, class: 'form-control', placeholder: 'Email'
                .name
                  = text_field_tag 'name', nil, class: 'form-control', placeholder: 'Name'
              .form-right
                = text_area_tag 'comments', nil, class: 'form-control', placeholder: 'Message'
            .row
              = submit_tag nil, class: 'form-control btn btn-default btn-about pull-right', id: 'submit', value: 'Send message to LongSword'
              %a.close-contact Close
        .col-md-2.col-sm-3.col-sm-2.facebook
          %a.hidden-xs{:href => "https://www.facebook.com/pages/LongSword-Vineyard/140545862685725", :target => "_blank"}
            .global-facebook
            %p For up to the minute offers and updates, visit us on Facebook!
.main-wrapper
  .inner-wrapper
    #visit
      .container
        %section.visit
          .row
            .col-sm-12
              %h1.section-title Visit LongSword
              %p LongSword is a breathtaking Chardonnay and Pinot Noir vineyard located in the heart of the Applegate Valley.
              %p A pleasant 15 minute drive from downtown Jacksonville, LongSword features table-ready wines that are distinctly approachable, charming, and complex.

        %section#patio.tasting-room
          .row
            .col-sm-12.content
              %h2.section-title Tasting room and patio
              %p Enjoy chatting with locals as you sample our wines in the tasting room or grab a bottle and spend a relaxing afternoon on the patio.
              %p Either way you'll be enchanted by breath-taking views of the vineyard and the surrounding mountains. Tastings are only $5 and lingering is encouraged.

        %section#vineyard.vineyard
          .row
            .col-sm-12.content
              %h2.section-title Vineyard
              %p Nestled between the Siskiyou, Cascade, and Coastal mountain ranges, LongSword encompasses 10 acres of Chardonnay and Pinot Noir vines and 12 acres of natural beauty.
              %p Thanks to the vineyard's unique microclimate, LongSword enjoys sunshine 360 days a year. Guests are often greeted by a delightful collection of farm animals that call LongSword home: 40 Plymouth Barred Rock chickens, 4 Pilgrim geese (led by the recalcitrant Louie), Will Feral (the elusive barn cat), and three Baby Doll Southdown sheep aptly named Einstein, Newton, and Hawking.

        %section#parasailing.parasailing
          .row
            .col-sm-12.content
              %h2.section-title Parasailing
              %p On any given afternoon, odds are you’ll see the colorful sails of hang gliders and parasailers growing large in the sky as they descend from Woodrat Mountain.
              %p Work your way through a bottle, and you'll probably even witness a daredevil landing or two in the field in front of the tasting room!
              %hr
              %p Interested in taking the plunge? Visit rvhpa.org to schedule a tandem flight and then land at LongSword for a glass of wine to celebrate your bravery.


    %section#wines
      .container
        .row
          .col-md-12.content
            %h1.section-title Our wines
            .row
              .col-sm-4.col-xs-12
                .image
                  %h3 Accolade
                  %img.wine{:src => image_url('accolade.jpg')}
                %p An enchanting, lightly sparkling Chardonnay known as "the wedding wine," Accolade delights and charms the palette for any occasion by combining playful notes of citrus with just a hint of sweetness for a truly effervescent experience!
              .col-sm-4.col-xs-12
                .image
                  %h3 Invitation
                  %img.wine{:src =>image_url('invitation.jpg')}
                %p Elegant and lively, Invitation is a unique non-oaked Chardonnay that pairs bright citrus and crisp mineral flavors with lovely notes of pear and melon to create a delightfully well-balanced, food-friendly wine.
              .col-sm-4.col-xs-12
                .image
                  %h3 Phrase
                  %img.wine{:src => image_url('phrase.jpg')}
                %p Beautifully rich and dark, Phrase features fragrant notes of blackberries and violets that unfurl into a spicy cardamom and pepper finish to create an unforgettable medium-bodied Pinot Noir.
            .row
              .col-sm-4.col-xs-12
                .image
                  %h3 Glissade
                  %img.wine{:src => image_url('accolade.jpg')}
                %p An enchanting, lightly sparkling Chardonnay known as "the wedding wine," Accolade delights and charms the palette for any occasion by combining playful notes of citrus with just a hint of sweetness for a truly effervescent experience!
              .col-sm-4.col-xs-12
                .image
                  %h3 Touché
                  %img.wine{:src =>image_url('invitation.jpg')}
                %p Elegant and lively, Invitation is a unique non-oaked Chardonnay that pairs bright citrus and crisp mineral flavors with lovely notes of pear and melon to create a delightfully well-balanced, food-friendly wine.
              .col-md-2
    %section#about
      .container
        .row
          .col-sm-12.content
            %h1.section-title About Us
            %p After thirty years working in the corporate world, Matthew Sorensen decided to trade in his suit and tie for jeans and work boots and head West. Armed with degrees in botany, biochemistry, and business, an unquenchable love of wine, and a fencing hobby, Matt set to work on creating LongSword Vineyard.
            %p From farm to bottle, Matt skillfully crafts each and every LongSword wine. As farmer, owner, and vintner of LongSword, he is passionate about producing wines that will delight and inspire his guests.
            %p Matt would like to thank the Applegate community, Tony, Teresa, Lola, and Rogue for their generosity in supporting his dream.
%footer
  .container
    .row
      .col-sm-3.col-xs-6
        %h3 Visit us
        %p
          8555 Highway 238
          %br Jacksonville, OR 97530
        %p
          %a.see-map{:href => "#", "data-toggle" => "modal", "data-target" => "#mapModal"} see it in the map &rarr;

      .col-sm-3.col-xs-6
        %h3 Tasting room
        %p
          Open 12pm - 5pm every day
      .clearfix.visible-xs
      .col-sm-3.col-xs-6
        %h3 Contact us
        %p
          %a{:href =>"tel:+15418991746"}541.899.1746
          %br contact@longsword.com
        %a{:href => "https://www.facebook.com/pages/LongSword-Vineyard/140545862685725", :target => "_blank"}
          .global-facebook-sm
      .col-sm-3.col-xs-6
        %h3 Credits
        %p
          &#169 2012-2013. LongSword Vineyard.
          %br All Rights Reserved.
          Photography by Kate Vangeloff
          %br Site Design by Jen Dorman
          Coded by Nathan Green
  %script{src: "http://maps.google.com/maps/api/js?v=3&sensor=false", type: "text/javascript"}
.modal.fade#mapModal
  .modal-dialog
    .modal-content
      .modal-header
        %h3.modal-title
          Get directions to
          %a{:target => "_blank", :href => "https://goo.gl/maps/YBqYc"} 8555 Highway 238, Jacksonville, OR 97530
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
      .modal-body
        #gmap_canvas{style: "height:350px; width: 100%;"}
      .modal-footer
        .closeModal{"data-dismiss" => "modal", type: "button"} Close

app/views/layouts/application.html.haml
!!!
/[if lt IE 7] <html class="ie lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7] <html class="ie lt-ie9 lt-ie8" lang="en">
/[if IE 8] <html class="ie lt-ie9" lang="en">
/[if IE 9 ]> <html lang="en" class="ie lt-ie10">
:plain
  <!--[if (gt IE 9)|!(IE)]>
%html{:lang => "en"}
  :plain
    <![endif]-->
  %head
    = csrf_meta_tags
    %meta{ :name => "viewport", :content => "width=device-width, user-scalable=no" }
    %meta{ :name => "apple-mobile-web-app-capable", :content => "yes"}

    %title LongSword Vineyard
    = yield :css_placeholder

  %body
    = yield
    = yield :end_of_body_placeholder

    = yield :js_placeholder
    %script
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', "#{ENV['GOOGLE_ANALYTICS']}", 'auto');
      ga('send', 'pageview');